# Load environment variables from .env file
Get-Content .env | ForEach-Object {
    if ($_ -match '^\s*([^=]+)=(.*)$') {
        [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim())
    }
}

# Load secrets from environment variables
$tenantId = [System.Environment]::GetEnvironmentVariable("TENANT_ID")
$subscriptionId = [System.Environment]::GetEnvironmentVariable("SUBSCRIPTION_ID")
$resourceGroup = [System.Environment]::GetEnvironmentVariable("RESOURCE_GROUP")
$dnsZone = [System.Environment]::GetEnvironmentVariable("DNS_ZONE")

$spName = "AzureDDNSUpdater"
$spRole = "DNS Zone Contributor"

az login --tenant $tenantId
$spOutput = az ad sp create-for-rbac --name $spName --role $spRole --scopes /subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Network/dnsZones/$dnsZone | ConvertFrom-Json

# Append the service principal credentials to .env file
Add-Content -Path .env -Value ""
Add-Content -Path .env -Value "# Service Principal Credentials (generated by azure_setup.ps1)"
Add-Content -Path .env -Value "CLIENT_ID=$($spOutput.appId)"
Add-Content -Path .env -Value "CLIENT_SECRET=$($spOutput.password)"

Write-Host "Service principal created successfully!"
Write-Host "The following credentials have been appended to .env:"
Write-Host "CLIENT_ID: $($spOutput.appId)"
Write-Host "CLIENT_SECRET: $($spOutput.password)"
Write-Host ""
Write-Host "Full output:"
$spOutput | ConvertTo-Json